name: Build
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
    - name: Install NPM Dependencies
      run: npm ci
      env:
        FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
    - name: Build Site
      run: npm run build
      env:
        FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        GATSBY_GOOGLE_MAPS_API_TOKEN: ${{ secrets.GATSBY_GOOGLE_MAPS_API_TOKEN }}
    - name: Rename Build Folder
      run: |
        rm -rf docs
        mv public docs
    - name: Build Resume
      run: npm run build-resume
      env:
        FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9
      with:
        add: docs
